
# Get all posts
# GET http://localhost:3000/posts HTTP/1.1


# Get 1 post
# GET http://localhost:3000/posts/1 HTTP/1.1
# GET http://localhost:3000/items/5 HTTP/1.1


# Create 1 post
# POST http://localhost:3000/lists HTTP/1.1
# content-type: application/json

# {
#     "id": 6,
#     "title": "topkek"
# }

# Delete 1 post
# DELETE http://localhost:3000/posts/3 HTTP/1.1