
# Get all posts
# GET http://localhost:3000/lists HTTP/1.1


# Get 1 post
# GET http://localhost:3000/posts/1 HTTP/1.1
# GET http://localhost:3000/items/5 HTTP/1.1


# Create 1 post
# POST http://localhost:3000/lists HTTP/1.1
# content-type: application/json

# {
#     "id": 6,
#     "title": "topkek"
# }

# PUT http://localhost:3000/lists/2 HTTP/1.1
# content-type: application/json

# {
#     "id": 6,
#     "title": "topkek",
#     "items": []
# }

# Delete 1 post
DELETE http://localhost:3000/lists/1 HTTP/1.1